name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install packages'
        run: 'npm ci'
        working-directory: ${{ env.API_PATH }}

      - name: 'Deploy'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
